name: SicilianDeliveryRush
options:
  bundleIdPrefix: com.andreaskviby
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_FILE: SicilianDeliveryRush/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    DEVELOPMENT_TEAM: ""

targets:
  SicilianDeliveryRush:
    type: application
    platform: iOS
    sources:
      - path: SicilianDeliveryRush
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.andreaskviby.SicilianDeliveryRush
        INFOPLIST_FILE: SicilianDeliveryRush/Info.plist
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTED_INTERFACE_ORIENTATIONS: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SUPPORTED_INTERFACE_ORIENTATIONS~ipad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    info:
      path: SicilianDeliveryRush/Info.plist
